### ISSUE TITLE
Can't compile Projects - miniCode 1.034 

### ISSUE THREAD

**Issue by seb5594** [lufinkey/miniCode#10]
Getting this error if i try to compile anything...
"error: invalid argument 'std=c++11' not allowed with 'C/ObjC'"

I created a empty project and it worked few times but then i got the same error message.
It's still the original source code (just a forms project).
Seems like it occurs only in the new version...
Please fix it asap

**Comment by seb5594** [comment]
I just downgraded to the version 1.033 and now it compile without any errors.
It's 100 % your update which break something

**Comment by lufinkey** [comment]
I'm aware. I know what the error is. I'm fixing it asap.

**Comment by lufinkey** [comment]
This should be fixed in the latest update, which should be up on Cydia within 24 hours (depending on when Optimo updates his repo)
