### ISSUE TITLE
On Xcode 6.1.1, iOS 8.1.2

### ISSUE THREAD

**Issue by ruslan120101** [lufinkey/miniCode#5]
In [multiple locations](https://github.com/lufinkey/miniCode/search?utf8=%E2%9C%93&q=%5Bname+setTextAlignment%3AUITextAlignmentCenter%5D%3B&type=Code), the line

[name setTextAlignment:UITextAlignmentCenter];

results in 
"Cannot initialize a parameter of type 'NSTextAlignment' with an rvalue of type 'UITextAlignment'

Seems like a cast helps build (have not* tested building yet), going from
```
[statusLabel setTextAlignment:UITextAlignmentLeft];
```

to

```
[statusLabel setTextAlignment:(NSTextAlignment)UITextAlignmentLeft];
```

**Comment by EthanArbuckle** [comment]
Don't cast it, just change it to NSTextAlignment. UITextAlignment is deprecated 

—
