### ISSUE TITLE
Builds in simulator after NSTextAlignment replaced UITextAlignment...

### ISSUE THREAD

**Issue by ruslan120101** [lufinkey/miniCode#6]
but on an actual iPhone cstdlib complains 
"No member named 'wcstombs' in the global namespace; did you mean wcsrtombs'?"

![screen shot 2015-02-04 at 9 04 32 pm](https://cloud.githubusercontent.com/assets/3612217/6053744/70040862-acb1-11e4-93f9-a99ccec2496b.png)

![screen shot 2015-02-04 at 9 04 24 pm](https://cloud.githubusercontent.com/assets/3612217/6053745/741f7aa8-acb1-11e4-9905-22b10447782f.png)

**Comment by lufinkey** [comment]
try setting it to std::wcstombs

**Comment by ruslan120101** [comment]
1. thanks for the quick reply
2. no dice

![screen shot 2015-02-04 at 9 20 34 pm](https://cloud.githubusercontent.com/assets/3612217/6053904/b002c47e-acb3-11e4-9e26-c0754456745b.png)

**Comment by lufinkey** [comment]
hm. let me look into that. Give me a moment to boot my VM

**Comment by lufinkey** [comment]
I just committed a possible fix. See if that works.

**Comment by lufinkey** [comment]
It should be noted that this project should be compiled with an older SDK to preserve compatibility

**Comment by ruslan120101** [comment]
maybe it's just an xcode 6.1.1 thing.... sick project btw.

![screen shot 2015-02-04 at 9 42 26 pm](https://cloud.githubusercontent.com/assets/3612217/6054090/baea271c-acb6-11e4-99a5-2fb630f160f0.png)

**Comment by lufinkey** [comment]
Thanks! I'm going to work on revising and rewriting a lot of it once I
finish rewriting my other project
